apiVersion: v1
kind: Secret
metadata:
  name: resource-service-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Riteshatri/resource-management-backend-resource-service-microservice.git
  username: riteshatri
  password: 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

# kubectl apply -f resource-repo-secret.yaml
 