apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: resource-mgmt
spec:
  selector:
    app: resource-service
  ports:
    - port: 8000
  # type: ClusterIP
  # type: LoadBalancer