apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: resource-mgmt
type: Opaque
stringData:
  AZURE_SQL_PASSWORD: Ritesh@12345
  SECRET_KEY: 00bfd5fadea7a8bcde64453b989e2f58a5f3718db3fb67e84e25aca777fab008
  GMAIL_APP_PASSWORD: vkqskadounrfxjdg

# kubectl apply -f .\Secret.yaml