apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resource
  namespace: argocd
spec:
  # project: default
  project: resource-project
  source:
    repoURL: https://github.com/Riteshatri/resource-management-backend-resource-service-microservice
    targetRevision: main
    path: heml/resource
  destination:
    server: https://kubernetes.default.svc
    namespace: resource-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# kubectl apply -f .\Applications.yaml
# kubectl get applications -n argocd
# kubectl get pods -n resource-management
# kubectl get svc -n resource-management